### ISSUE TITLE
Player Quit Event Error. Does not work well with Per World Plugins

### ISSUE THREAD

**Issue by Skalylikesbudder** [NiklasEi/GameBox#15]
This is the start of the error. what happens is a player presses esc and it causes this error where the event does not work. You might need to either stop players from doing that or add more door signs to close out the gui. idk though

https://pastebin.com/zEyL2L8K

**Comment by NiklasEi** [comment]
[`mainShop` seems to be null.](https://github.com/NiklasEi/GameBox/blob/master/GameBox/src/main/java/me/nikl/gamebox/guis/shop/ShopManager.java#L195)

I'll look into this when I come back from my vacation.

**Comment by NiklasEi** [comment]
What per world plugin specifically do you think is causing the error?

**Comment by NiklasEi** [comment]
Which version of PerWorldPlugins are you using? I found the old thread on Bukkit, but the last update was 2015. On SpigotMC there are two different authors who continued the plugin. Can you send me a link to the version you are using, so I can test my fix?
