### ISSUE TITLE
Sound Message.

### ISSUE THREAD

**Issue by TheIntelloBox** [NiklasEi/GameBox#20]
Hi !

I customized the sound messages in GameBox. 
But on my server, sound messages are in English but I customized it in French...

Can you see if it's a problem ?

**Comment by NiklasEi** [comment]
You mean the lore of the sound on/off button?

**Comment by TheIntelloBox** [comment]
Yeah !

**Comment by NiklasEi** [comment]
For me it works without any problems.

Have you changed the correct messages? Is the change in the file that is configured as language file in the configuration file?

**Comment by TheIntelloBox** [comment]
Yes I did all good I think.

**Comment by NiklasEi** [comment]
post your config and language file

**Comment by TheIntelloBox** [comment]
config.yml : https://hastebin.com/udocovaqey.bash
lang_en.yml : https://hastebin.com/divikahapa.bash

**Comment by NiklasEi** [comment]
All the other messages work? 

I just remembered that I fixed a bug related to those messages a while ago. If you click the button once, does the language update then? That problem was solved in commit a902ef5f030d45a9a9bcd1877df6bdb8c0d2e951, which will be included in the next update.

**Comment by NiklasEi** [comment]
Fix is included in release 1.5.10
