### ISSUE TITLE
When is the V.2 ? :D

### ISSUE THREAD

**Issue by TheIntelloBox** [NiklasEi/GameBox#23]
Hey,

When is the V.2 ? :D

**Comment by NiklasEi** [comment]
My exam phase ends end of February. I will release the first v2 in March i guess, but please don't quote me on it ^^

The core features are done. I only need to add top lists in MySQL and then thoroughly debug everything. After that I will feel OK with releasing the first v2. There are still a lot of features planed and a lot I want to rewrite, but there simply isn't enough time and I want to start writing games again.

If you want to see now and then how v2 is looking in game, pm me on spigot and I'll give you my testserver's details.
