### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by TheIntelloBox** [NiklasEi/gamebox#52]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-1-development-builds.336415/

**Comment by TheIntelloBox** [comment]
Nop, unfortunately. :/

**Comment by NiklasEi** [comment]
After adding 1.13.1 support to my nmsutilities, I didn't encounter any other problems with GameBox on that version.
