### ISSUE TITLE
Teleporting closes gamebox inventory

### ISSUE THREAD

**Issue by Miclebrick** [NiklasEi/gamebox#54]
Players being moved closes the gamebox inventory. Not sure if this can be fixed but you can keep player inventories open, perhaps you can update the position of the inventory to match their coordinates? I have moving ships on my server and I want people to be able to play minigames during long voyages to pass the time.

**Comment by NiklasEi** [comment]
I am quite sure, that I cannot do anything against that. Teleporting the players will always close an open inventory.

**Comment by Matocolotoe** [comment]
You might be able to check if a player has a GameBox inventory opened in a teleport event to re-open it ?

**Comment by Miclebrick** [comment]
You might also be able to use NMS to do that, iirc I had to manually close player's inventory when I was making a smooth teleport method

**Comment by NiklasEi** [comment]
If you have control over the plugin that makes those ships move, you should implement the smooth teleport function at that point then. I cannot replace all teleports with a different kind just to keep the inventories from closing.
