### ISSUE TITLE
Mavenize 

### ISSUE THREAD

**Issue by RoboMWM** [NiklasEi/GameBox#6]
LaxWasHere was gonna PR the InventoryHolder to your repo, but it isn't mavenized, and it seems like a lot of work to gather all the dependencies.

Maven is a way to manage dependencies, and also allows others to easily import your project to PR.

![](http://i.imgur.com/VQVnIev.png)

**Comment by NiklasEi** [comment]
> LaxWasHere was gonna PR the InventoryHolder to your repo, but it isn't mavenized, and it seems like a lot of work to gather all the dependencies.

Yes, that's exactly what I noticed when I wanted to start using maven, so I kept on delaying that problem. At the moment it was always easier to simply add the dependency for the local project.

- NMS from 1.8 - 1.12
- Vault
- PlaceholderAPI
- bStats

I'll getting started at that in some study-free hours. Would be really nice if I finally managed to get rid of the manual dependeny hell. Maybe you could assist me when I run into problems. 

I'll keep you posted in this issue.

**Comment by LaxWasHere** [comment]
We're in [hell](kiwiirc.com/client/irc.spi.gt/#hell) if you need any help.

**Comment by NiklasEi** [comment]
making slow progress https://github.com/NiklasEi/GameBox/tree/mavenize

**Comment by NiklasEi** [comment]
Could one of you varify that the current mavenize branch can be imported as is?

I fixed all remaining problems and can now compile a functional .jar.

**Comment by RoboMWM** [comment]
Oooh modules, something I haven't had to resort to doing yet.

Will test shortly..

**Comment by RoboMWM** [comment]
Yup, seems to compile just fine here.
