### ISSUE TITLE
Item pickup bug when open menu

### ISSUE THREAD

**Issue by andris155** [NiklasEi/gamebox#64]
https://www.youtube.com/watch?v=6hi3pjgMeGQ

**Comment by Matocolotoe** [comment]
This kind of problem has already happened for me (#47).
Try to set a lower priority (from highest to high for example) for your item pickup event cancel thing

**Comment by NiklasEi** [comment]
As far as I understood this is not exactly the same issue. Even when GameBox picks up items they should not appear in your game inventory but should show up in your inventory after you close the game. I don't know though whether this is really a bug in GameBox or a glitch that depends on you getting the perfect timing to open the inventory. I will try to debug this when I get back to my programming projects.

**Comment by Matocolotoe** [comment]
i will thonk about this
