### ISSUE TITLE
ALL-IN-ONE GameBox

### ISSUE THREAD

**Issue by McKl1992** [NiklasEi/gamebox#66]
Es wäre eine super Idee, GameBox mit allen Spielen zu Integrieren.
So das man nicht alle Spiele als .jar Downloaden und Installieren muss.
Problem hier ist nämlich das diese auch als Extra Plugin erkannt, angezeigt, geladen werden.

Ein ALL-IN-ONE wäre hier eine super Lösung.
So hat man nur 1 Plugin was geladen werden muss mit allen Spielen.

Liebe Grüße

**Comment by Matocolotoe** [comment]
Ich denke, ein Plugin, das 5 Plugins enthält, verbraucht so viele Ressourcen wie diese 5 Plugins

**Comment by NiklasEi** [comment]
Ich glaube es geht eher um die Anzahl der Einträge in der Pluginliste und die Anzahl der plugins, die geupdatet werden müssen. Oder @McKl1992 ?

**Comment by McKl1992** [comment]
Genau. @NiklasEi :)

**Comment by NiklasEi** [comment]
V3 will take care of this with modules that can be installed ingame.
