### ISSUE TITLE
Load the database async

### ISSUE THREAD

**Issue by RoboMWM** [NiklasEi/gamebox#67]
Server log effectively freezes for around 20 seconds. There's no indication that Gamebox is the culprit, but fortunately timings helped find that out. Would highly suggest printing out any file IO, especially if on main thread... which this file IO should be on an async thread.

https://timings.aikar.co/?id=1deb4b544370438a88b9793d348920de

![](https://i.imgur.com/eM44GSr.png)

Version 2.2.4 as per plugins tab in timings.

**Comment by NiklasEi** [comment]
For now I am logging the IO. If the loading takes too long, MySQL should be used instead of the flatfile db anyways. 
I started a branch for async db loading. As it turns out I would have to change a lot to make that happen without a bunch of new issues.

**Comment by RoboMWM** [comment]
If you insist on using SQL, then sqlite (or other flatfile storage options like H2) should be an option. I don't have any need to run a MySQL instance, especially since I only use this on a single server instance (and don't have any other plugin that requires a MySQL backend).

I'm assuming your MySQL queries are async? (They definitely should be.)

Also, minor critique, but unsure why you closed this if the issue still exists - it's in progress yes, but not finished.

**Comment by NiklasEi** [comment]
> If you insist on using SQL, then sqlite (or other flatfile storage options like H2) should be an option. I don't have any need to run a MySQL instance, especially since I only use this on a single server instance (and don't have any other plugin that requires a MySQL backend).
I could, of course, add support for an additional SQL DBs.

> I'm assuming your MySQL queries are async? (They definitely should be.)
Sure they are.

I closed it for the "Would highly suggest printing out any file IO" part. But you are right, the async loading is not done yet.

**Comment by RoboMWM** [comment]
I think you're using ACF, you can also use Aikar's taskchain to help execute code and pass data between sync and async threads.

**Comment by NiklasEi** [comment]
I looked into taskchain a while ago and it is definetely a nice tool. Though for the moment I'll handle it in callback hell. I might find the time in the next months to start with a new major version. In that case taskchain will be used.

**Comment by RoboMWM** [comment]
There's very little to setup (just a couple of static calls), I thought it'd be a lot but when I actually used it, it was much easier than doing callbacks, especially since it uses lambdas in the examples.

**Comment by RoboMWM** [comment]
There's very little to setup (just a couple of static calls), I thought it'd be a lot but when I actually used it, it was much easier than doing callbacks, especially since it uses lambdas in the examples.

https://github.com/RoboMWM/MidnightPortal/blob/master/src/main/java/com/robomwm/midnightportal/MidnightPortal.java#L27 for setup and https://github.com/RoboMWM/MidnightPortal/blob/master/src/main/java/com/robomwm/midnightportal/PortalUtils.java#L84 for using.

**Comment by NiklasEi** [comment]
Looking at the timings report you probably have a large data file, right? Could you send that to me so I can test with it?

**Comment by RoboMWM** [comment]
That or the HDD is slow, could be either or both. https://hasteb.in/gatotubi.yaml from `plugins/GameBox/data.yml`

**Comment by NiklasEi** [comment]
Thank you for the file.

The empty entries were fixed in #65. Although I probably should implement a clean-up to actively remove players that just have default settings and no stats.
