### ISSUE TITLE
Use plugin logger for error messages

### ISSUE THREAD

**Issue by RoboMWM** [NiklasEi/gamebox#68]
You should consider using the plugin logger here so the plugin name shows up along with the message here.

https://github.com/NiklasEi/gamebox/blob/25a0693ea71b53104dc3eea2717ed5bad474ea8e/core/src/main/java/me/nikl/gamebox/PluginManager.java#L399

If I find time and don't forget (and am not beat to it) I'll PR this.

**Comment by NiklasEi** [comment]
There are some uses of ConsoleSender left, but they also print the plugin name and use colour.
