### ISSUE TITLE
(!) IMPORTANT(!)Bugg 1.8.8 Spigot - Command failed to start! 

### ISSUE THREAD

**Issue by MineSquare** [NiklasEi/GameBox#7]
I have a Minecraft Spigot 1.8.8 (joinable 1.8 -1.12)Server. I found your Plugin amazing, but not in  1.8(.8)...
If I write /gb or /gamebox a error syntex join the chat. [International ERROR]- Please help me!
I can give you money for a compatibel Premium Version!!!
---
Please contact me :1st_place_medal: 
Server: smiles.terminal.run
           :terminal.run:27673
---
Email: smiles.terminal.run
Skype: magnus7361
---
Peace Out,
Smiles

**Comment by NiklasEi** [comment]
Full stacktrace please

**Comment by MineSquare** [comment]
More informations or?
"Full stacktrace''

**Comment by MineSquare** [comment]
Sorry, but I don't know the Word Stacktrace... I am from Germany and my english skills are really bad.
In 1.5.5 is 1.8 included, my problem is the command /gb or /gamebox is not working. The answer of the command is a message with International Error.
In 1.5.4/1.5.3 is the chat message "/gamebox" and than nothing; no GUI, nothing
Can you fix it?

**Comment by NiklasEi** [comment]
Kopier bitte den gesamten Fehler aus der Konsole.

**Comment by MineSquare** [comment]
10.08 12:51:32  [Server]  INFO ... 15 mehr
 10.08 12:51:32  [Server]  INFO bei org.bukkit.command.PluginCommand.execute (PluginCommand.java:44) ~ [Zapfen-1.8.8. Jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei mir.nikl.gamebox.commands.MainCommand.onCommand (MainCommand.java:66) ~ [?:?]
 10.08 12:51: 32  [Server]  INFO bei me.nikl.gamebox.guis.GUIManager.openMainGui (GUIManager.java:224) ~ [?:?]
 10.08 12:51:32  [Server]  INFO bei mir.nikl.gamebox.guis.gui .MainGui.open (MainGui.java:95) ~ [?:?]
 10.08 12:51:32  [Server]  INFO bei mir.nikl.gamebox.guis.gui.MainGui.loadMainGui (MainGui.java:131) ~ [ ?:
?] 10.08 12:51:32  [Server]  INFO bei org.bukkit.Bukkit.createInventory (Bukkit.java:938) ~ [spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51: 32  [Server]  INFO bei org.bukkit.craftbukkit.v1_8_R3.CraftServer.createInventory (CraftServer.java:1525) ~ [spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server ]  INFO bei org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom. <Init> (CraftInventoryCustom.java:32) ~ [spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [ Server]  INFO bei org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom $ MinecraftInventory <init> (CraftInventoryCustom.java:59) ~ [spigot-1.8.8.jar:
Git-Spigot-db6de12-18fbb24] 10.08 12:51:32  [Server]  INFO bei org.apache.commons.lang.Validate.isTrue (Validate.java:136) ~ [spigot-1.8.8.jar: git-Spigot -db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO Verursacht durch: java.lang.IllegalArgumentException: Titel darf nicht länger als 32 Zeichen sein
 10.08 12:51:32  [Server]  INFO bei java.lang.Thread.run ( Thread.java:748) [?: 1.8.0_144]
 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.MinecraftServer.run (MinecraftServer.java:557) [spigot-1.8.8.jar : Git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.MinecraftServer.A (MinecraftServer.java:
654) [spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24] 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.DedicatedServer.B (DedicatedServer.java:374) [Zapfen -1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.MinecraftServer.B (MinecraftServer.java:715) [Zapfen-1.8.8 .jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.SystemUtils.a (SourceFile: 44) [spigot-1.8.8.jar: git-Spigot -db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei java.util.concurrent.FutureTask.run (FutureTask.java:266) [?: 1.8.0_144]
 10.08 12:51:32  [Server]  INFO an Java.
Util.concurrent.Executors $ RunnableAdapter.call (Executors.java:511) [?: 1.8.0_144] 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.PlayerConnectionUtils $ 1.run (SourceFile: 13 ) [Spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.PacketPlayInChat.a (PacketPlayInChat.java:1) [Zapfen- 1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.PacketPlayInChat.a (PacketPlayInChat.java:45) [Zapfen-1.8.8. Jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.PlayerConnection.a (SpielerConnection.java:997) [spigot-1.8.8.jar:
Git-Spigot-db6de12-18fbb24] 10.08 12:51:32  [Server]  INFO bei net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand (SpielerConnection.java:1162) [spigot-1.8.8.jar: git-Spigot- Db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO bei org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand (CraftServer.java:641) ~ [spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24 ]
 10.08 12:51:32  [Server]  INFO bei org.bukkit.command.SimpleCommandMap.dispatch (SimpleCommandMap.java:141) ~ [spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51 : 32  [Server]  INFO bei org.bukkit.command.PluginCommand.execute (PluginCommand.java:46) ~ [spigot-1.8.8.jar: git-Spigot-db6de12-18fbb24]
 10.08 12:51:32  [Server]  INFO org.bukkit.command.CommandException: Unbehandelte Ausnahme Ausführen Befehl 'gb' im Plugin GameBox v1.5.5
 10.08 12:51:32  [Server]  ERROR null
 10.08 12:51:32  [Server ]  INFO Smiles14 ausgegebener Serverbefehl: / gb
---
Wow this is a ERROR xD

**Comment by NiklasEi** [comment]
>  10.08 12:51:32 [Server] INFO Verursacht durch: java.lang.IllegalArgumentException: Titel darf nicht länger als 32 Zeichen sein

Das ist der wichtige Teil. Du bist auf einer total veralteten Spigot version, die nicht mit Inventartiteln mit einer Länge von über 32 Zeichen klar kommt. Mach dir ein eigenes languagefile und kürze ALLE titel. Das musst du auch für alle Spiele machen, sonst kommt der gleiche Fehler beim öffnen von Spielen.

Oder wechsel auf Spigot 1.9+ ...

**Comment by MineSquare** [comment]
Ahh thanks I use 1.8 because 1.8-1.12 ... All big Server use 1.8

**Comment by MineSquare** [comment]
Good luck
