### ISSUE TITLE
cookieclicker 2.2.2 not in maven repo

### ISSUE THREAD

**Issue by RoboMWM** [NiklasEi/gamebox#70]
When building this repo, one of the goals fails (I believe it was distribution) due to not finding cookieclicker 2.2.2.

`[ERROR] Failed to execute goal on project gamebox-distribution: Could not resolve dependencies for project me.nikl:gamebox-distribution:jar:2.2.5: Could not find artifact me.nikl:cookieclicker:jar:2.2.2 in nikl-repo (http://repo.nikl.me/artifactory/public)`

**Comment by NiklasEi** [comment]
It's deployed now. Thank you for reporting this.
