### ISSUE TITLE
UPDATE 1.15.2

### ISSUE THREAD

**Issue by successed** [NiklasEi/gamebox#77]
PLEASE UPDATE 1.15.2

**Comment by NiklasEi** [comment]
Current beta version: [download](https://ufile.io/aelziwvm)
If you want regular updates, please join my discord: [support.nikl.me](support.nikl.me)

I'll leave this open until the version is officially published on Spigot

**Comment by successed** [comment]
> Current beta version: [download](https://ufile.io/aelziwvm)
> If you want regular updates, please join my discord: [support.nikl.me](http://support.nikl.me)
> 
> I'll leave this open until the version is officially published on Spigot

/gba reload is not'a workt.

**Comment by NiklasEi** [comment]
I am also running the plugin and the games on a 1.15 server and `/gba reload` is working fine. Can you give me some more info, please? Any errors in the console?

**Comment by swaro32** [comment]
Can you upload this to Mediafire please? Uploadfiles requires a $9/m subscribe to download.

**Comment by NiklasEi** [comment]
When clicking on the download link you should choose the "Free download" button. Then you do not need to pay.

**Comment by NiklasEi** [comment]
Published on Spigot: https://www.spigotmc.org/resources/gamebox-inventory-games-collection.37273/update?update=329849
