### ISSUE TITLE
Unknown Translation Key

### ISSUE THREAD

**Issue by RoboMWM** [NiklasEi/GameBox#8]
This shows up as a prefix to the title/name of the inventory (e.g. it appears before CC is printed for cookie clicker. Causes larger titles like the score in minesweeper to flow off of the inventory window :P ).

I'm assuming this is because you assume `player#getLocale` returns null for `en_us`, but paper fixed that issue. This is a guess though since I used github search for the "Unknown Translation Key" text but could not find any results.

**Comment by NiklasEi** [comment]
I just tested all games with Paper#1193 and everthing works as expected. I can't find "Unknown Translation Key" anywhere.

**Comment by RoboMWM** [comment]
Hmm, not sure if this was due to an update or what, but it seems the "langfile" in the config was set to `default`, not `lang_en`

Weird.

Sorry about not checking earlier, was going to do that but got distracted and forgot lol.

**Comment by RoboMWM** [comment]
Hmm, seems `default` is a valid value. Setting it to `lang_en` or `lang_en.yml` made no difference, I still have it appearing. https://i.imgur.com/LlMzLZN.png

I also use another inventory game system called InvGame, and that one doesn't have issues with the menu name. So not sure what specifically is going on, but it's localized to GameBox.

**Comment by NiklasEi** [comment]
'default' uses lang_en from the jar whereas 'lang_en' uses lang_en.yml from the language folder.

Still no clue what could be the issue here, but I'll look into it again.

**Comment by NiklasEi** [comment]
I can't replicate this issue with any of the latest paper builds. Have you heard from anyone else with a similar problem?

**Comment by NiklasEi** [comment]
I finally found the problem due to a hint from PhanaticD in the GameBox discussion. This is caused by protocol support, because I was using ChatMessages to update the inventory titles (which are translatable...).

**Comment by RoboMWM** [comment]
Ah, I kinda figured that would've been a factor but I guess I never tested that (although some part of me wants to say I did... I guess I never got to it). Thanks!
