### ISSUE TITLE
issue or just a hardcode info?

### ISSUE THREAD

**Issue by CloudeLecaw** [NiklasEi/gamebox#85]
Does the cookieclickermodul really update?
i get this info on every restart of the server...
**_gamebox 3.2.0 - papermc 1.16.5_**

![image](https://user-images.githubusercontent.com/12080017/107608617-c7bfb780-6c3c-11eb-9447-94339b169d14.png)

**Comment by NiklasEi** [comment]
Hey, thanks for the info!
This was due to a misconfiguration in the CookieClicker build and should only happen one more time now.
