### ISSUE TITLE
MineSweeper Minigame Broke server

### ISSUE THREAD

**Issue by TiaTheFairy** [NiklasEi/gamebox#92]
Only in Hard Mode, when I click a glass pane, I take it out of the inventory, then the server stop responding, console got spammed, then server stoped.

Errors when server crash : [log.txt](https://github.com/NiklasEi/gamebox/files/9692005/log.txt)
Minesweeper Config file (.yml is not allowed on github, so I renamed it to .txt when uploading) :  [config.txt](https://github.com/NiklasEi/gamebox/files/9692010/config.txt)

**Comment by NiklasEi** [comment]
The server log suggests a parsing error in your yaml files. If the issue still persists: could you post the yaml files please?
